### ISSUE TITLE
Swift package Manager

### ISSUE THREAD

**Issue by gowthamravi** [zekunyan/TTGSnackbar#70]
Can you able to add the spm to live version??

<img width="734" alt="image" src="https://user-images.githubusercontent.com/6426453/68109509-adaf0980-ff10-11e9-84b0-f787e1f8efe6.png">

**Comment by zekunyan** [comment]
I have not try it yet. Maybe you can fix it and make a PR ? ~~

**Comment by dsaiko** [comment]
No pull request required.

Error means that Package.swift file is not part of source code tagged by version 1.8.0.
It´s available only in master branch.

What would help is to tag a new version which would include Package.swift.

Till then, user needs to reference master branch or commit instead of 1.8.0 version.

**Comment by zekunyan** [comment]
The new version 1.9.0 has fixed this.

**Comment by gowthamravi** [comment]
thanxs bro!
